services:
  postgres-compose:
    container_name: postgres-container
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=nexbuy-db
    networks:
      - nexbuy-network

  rabbitmq-compose:
    image: rabbitmq:4.1.3-management
    container_name: rabbitmq-container
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    networks:
      - nexbuy-network

  stripe-compose:
    image: stripe/stripe-cli:latest
    container_name: stripe-container
    command: listen --forward-to host.docker.internal:8080/api/v1/payments/webhook
    environment:
      - STRIPE_API_KEY=sk_test_51S2aEwL5m5xYnChqMEg3sE12qRRCarFTaISmTLraG0WpIyDzCZwBfJccvDIhKujkjRAi91Gy7eYTuNrIxTj5rXD700QVzrmpIS
    ports:
      - "12111:12111"
    networks:
      - nexbuy-network

networks:
  nexbuy-network:
    driver: bridge