spring:
  application:
    name: nexbuy

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  api:
    security:
      token:
        secret: ${JWT_SECRET:jwt_secret_key}

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

  rabbitmq:
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 4
          initial-interval: 3000
          multiplier: 2
          max-interval: 12000

  freight:
    api:
      url: ${FREIGHT_QUOTE_URL}
      token: ${FREIGHT_QUOTE_TOKEN}
      email: ${FREIGHT_QUOTE_EMAIL}
      cep:
        from: ${FREIGHT_QUOTE_FROM}

  stripe:
    api:
      secret:
        key: ${STRIPE_API_SECRET_KEY}
      webhook:
        secret:
          key: ${STRIPE_WEBHOOK_SECRET_KEY}