spring:
  application:
    name: nexbuy

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  api:
    security:
      token:
        secret: ${JWT_SECRET:jwt_secret_key}

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

  rabbitmq:
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 4
          initial-interval: 3000
          multiplier: 2
          max-interval: 12000
    queues:
      user-created:
        queue: user.created.queue
        exchange: user.created.exchange
        routing-key: user.created.routing.key
        dlq:
          queue: user.created.dlq.queue
          exchange: user.created.dlq.exchange
          routing-key: user.created.dlq.routing.key
      user-code-created:
        queue: user.code.created.queue
        exchange: user.code.created.exchange
        routing-key: user.code.created.routing.key
        dlq:
          queue: user.code.created.dlq.queue
          exchange: user.code.created.dlq.exchange
          routing-key: user.code.created.dlq.routing.key
      product-registered:
        queue: product.registered.queue
        exchange: product.registered.exchange
        routing-key: product.registered.routing.key
        dlq:
          queue: product.registered.dlq.queue
          exchange: product.registered.dlq.exchange
          routing-key: product.registered.dlq.routing.key
      product-sku-updated:
        queue: product.sku.updated.queue
        exchange: product.sku.updated.exchange
        routing-key: product.sku.updated.routing.key
        dlq:
          queue: product.sku.updated.dlq.queue
          exchange: product.sku.updated.dlq.exchange
          routing-key: product.sku.updated.dlq.routing.key
